### ISSUE TITLE
Woot maintainance ?

### ISSUE THREAD

**Issue by jpic** [Spredzy/python-c14#8]
Salut Yanis !

Me permettez vous de demander si vous avez actuellement ce module en production ?

Merci !

**Comment by Spredzy** [comment]
Bonjour @jpic 

Desole pour le retard dans ma reponse. Les fetes sont passees par la.
Non ce module n'est pas utilise en production, ni de fait maintenu actuellement.

Le projet pour lequel ce module avait ete cree n'a, au final, jamais vu le jour.

Si la reprise de la maintenance de ce projet vous interesse, faites moi signe, ce serai avec plaisir de le voir continuer a vivre.

Bonne journee,

**Comment by jpic** [comment]
Merci Yanis, suite a l'etude de l'epique j'ai decide d'attendre qu'on encaisse encore 6 mois de data.

++
